### ISSUE TITLE
Possible Typo

### ISSUE THREAD

**Issue by bobbyyan0** [chrisyeh96/chrisyeh96.github.io#11]
Should the "test/packA/," in "2. Use absolute imports rooted at the test/ directory (i.e., middle column in the table above). This guarantees that running start.py directly will always work. In order to run a2.py directly, we can modify sys.path in a2.py to include test/packA/, before sa2 is imported." of https://chrisyeh96.github.io/2017/08/08/definitive-guide-python-imports.html#case-2-syspath-could-change be "test/" instead? Thank you.

**Comment by chrisyeh96** [comment]
Good catch, you are correct. This has been fixed!
