### ISSUE TITLE
Cannot replicate your page about LQR

### ISSUE THREAD

**Issue by RichardPoes** [chrisyeh96/chrisyeh96.github.io#18]
Hi Chris,
Sorry to message you in this way; I could not find another way.
I was trying to set up my own math blog via GitHub pages, however, the Math does not seem to render as easily as in your page. Thus, I copied your page about LQR to my blog, and tried to make it render the same way as your blog. It can be found [here](https://richardpoes.github.io/tests/). I was wondering if you knew what was going wrong. 
I do realize you probably have better things to do than to help me debug, but it was worth a shot.

**Comment by chrisyeh96** [comment]
I think your issue is that you're unnecessarily calling `markdownify`:

```
    {{content | markdownify}}
```
See https://github.com/RichardPoes/RichardPoes.github.io/blob/23e4b592cd8ba75038d95e55509d1d8b85907f60/_layouts/post.html#L22

Try replacing that line with just
```
    {{content}}
```
