### ISSUE TITLE
module import precedence mistake in the Python imports article

### ISSUE THREAD

**Issue by etene** [chrisyeh96/chrisyeh96.github.io#2]
Hello,

First of all excuse me if this isn't the right place to post this, i didn't really know how to get in touch so I figured a Github issue would be the best way to do it.

I was reading your post regarding imports (https://chrisyeh96.github.io/2017/08/08/definitive-guide-python-imports.html), which I found instructive & well written, but there's a small point I think is wrong.

Here's the excerpt:

> The Python documentation goes on to mention the following:
>> The directory containing the script being run is placed at the beginning of the search path, ahead of the standard library path. This means that scripts in that directory will be loaded instead of modules of the same name in the library directory.

> This seems to be a mistake. For example, calling import math in start.py will import the standard math module, NOT my own math.py file in the same directory.

The documentation is correct: the described behavior applies to modules *in the standard library directory*. The `math` module is a builtin module (like the `sys` module), guaranteed to be always available, and thus not implemented as a separate Python file in the standard library.

If you name your own module `argparse` for example, it will indeed have precedence over the `argparse` module in the standard library.

Hope I was clear, and thanks again for your excellent post. Cheers !

**Comment by Elune0syh** [comment]
It`s strange if you do somethings like these inside test dir
* `touch collections.py`
* `python`
* `import collections`

the collections standard module will be imported other than the collections.py
Also `Ipython` behaves different than the standard python interpreter, `Ipython` will always import the standard library instend of `random.py / collections.py` under test dir

Env: virtualenv python3.6.5

**Comment by memocong** [comment]
@chrisyeh96 ，thanks a lot for your well-organized and instructive post regarding [python import](https://chrisyeh96.github.io/2017/08/08/definitive-guide-python-imports.html). For module import precedence on built-in modules , similar to this [article](https://stackoverflow.com/questions/58347478/import-operation-behaves-differently-if-i-name-script-string-py-or-math-py), it's proved on my computer (MacOS Mojave, python 3.6/3.7)  that _math_ is not in _sys.builtin_module_names_ and the _math.py_ file in my working directory will be imported before builtin module _math_. So, I think only those "builtin modules" in _sys.builtin_module_names_ have precedence over the directory containing the script. 

ps: here, builtin modules refer to those 

> Some modules are written in C and built in to the Python interpreter

. reference [python doc](https://docs.python.org/3/library/intro.html).

Below is the output information of _math_ module.
`
&gt;&gt;&gt; import math

&gt;&gt;&gt; math

<module 'math' from '/Users/xxxx/.pyenv/versions/3.6.5/lib/python3.6/lib-dynload/math.cpython-36m-darwin.so'>
`
